//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKHL.ProjectSweeper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKHL.ProjectSweeper.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This produce is no longer being updated..
        /// </summary>
        internal static string ABOUT_Desc_Txt1 {
            get {
                return ResourceManager.GetString("ABOUT_Desc_Txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is licensed to.
        /// </summary>
        internal static string ABOUT_Desc_Txt2 {
            get {
                return ResourceManager.GetString("ABOUT_Desc_Txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is not licensed..
        /// </summary>
        internal static string ABOUT_Desc_Txt3 {
            get {
                return ResourceManager.GetString("ABOUT_Desc_Txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about software version and updates.
        /// </summary>
        internal static string ABOUT_IconTip {
            get {
                return ResourceManager.GetString("ABOUT_IconTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find this software listed in updates..
        /// </summary>
        internal static string ABOUT_RSLT_Txt1 {
            get {
                return ResourceManager.GetString("ABOUT_RSLT_Txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of {0} is available. Version {1} is available at www.pkhlineworks.ca..
        /// </summary>
        internal static string ABOUT_RSLT_Txt2 {
            get {
                return ResourceManager.GetString("ABOUT_RSLT_Txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your product is up to date..
        /// </summary>
        internal static string ABOUT_RSLT_Txt3 {
            get {
                return ResourceManager.GetString("ABOUT_RSLT_Txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not contact server to check for updates..
        /// </summary>
        internal static string ABOUT_RSLT_Txt4 {
            get {
                return ResourceManager.GetString("ABOUT_RSLT_Txt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT_Title {
            get {
                return ResourceManager.GetString("ABOUT_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string Complex {
            get {
                return ResourceManager.GetString("Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default:.
        /// </summary>
        internal static string DefaultMenuitem {
            get {
                return ResourceManager.GetString("DefaultMenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string DeleteAllButton {
            get {
                return ResourceManager.GetString("DeleteAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to delete this style.
        /// </summary>
        internal static string DeleteCheckboxTip {
            get {
                return ResourceManager.GetString("DeleteCheckboxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete source pattern?.
        /// </summary>
        internal static string DeleteSourcePatternCheckbox {
            get {
                return ResourceManager.GetString("DeleteSourcePatternCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete source style?.
        /// </summary>
        internal static string DeleteSourceStyleCheckbox {
            get {
                return ResourceManager.GetString("DeleteSourceStyleCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style {0} is already being converted to {1}. This could lead to unpredictable results..
        /// </summary>
        internal static string DIA001_MainCont {
            get {
                return ResourceManager.GetString("DIA001_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is being converted to this style..
        /// </summary>
        internal static string DIA001_MainInst {
            get {
                return ResourceManager.GetString("DIA001_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the default style to another style before trying to delete all the elements using this style..
        /// </summary>
        internal static string DIA002_MainCont {
            get {
                return ResourceManager.GetString("DIA002_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is the default style..
        /// </summary>
        internal static string DIA002_MainInst {
            get {
                return ResourceManager.GetString("DIA002_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some styles were set to be converted to {0}. These styles have been reset..
        /// </summary>
        internal static string DIA003_MainCont {
            get {
                return ResourceManager.GetString("DIA003_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all the selected elements where valid. Starting in All mode instead..
        /// </summary>
        internal static string DIA004_Txt {
            get {
                return ResourceManager.GetString("DIA004_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup group: {0} and change the element..
        /// </summary>
        internal static string DIA006_Command1 {
            get {
                return ResourceManager.GetString("DIA006_Command1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the group unchanged. (The style will not be deleted)..
        /// </summary>
        internal static string DIA006_Command2 {
            get {
                return ResourceManager.GetString("DIA006_Command2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element using the {0} style was found in the group {1}.
        /// </summary>
        internal static string DIA006_MainInst {
            get {
                return ResourceManager.GetString("DIA006_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found group.
        /// </summary>
        internal static string DIA006_Title {
            get {
                return ResourceManager.GetString("DIA006_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a name for the new template..
        /// </summary>
        internal static string DIA007_MainCont {
            get {
                return ResourceManager.GetString("DIA007_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name required..
        /// </summary>
        internal static string DIA007_MainInstr {
            get {
                return ResourceManager.GetString("DIA007_MainInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm overwrite.
        /// </summary>
        internal static string DIA008_MsgBxCapt {
            get {
                return ResourceManager.GetString("DIA008_MsgBxCapt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite this template?.
        /// </summary>
        internal static string DIA008_MsgBxTxt {
            get {
                return ResourceManager.GetString("DIA008_MsgBxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected to delete a saved template. This cannot be undone. Are you sure you want to continue?.
        /// </summary>
        internal static string DIA009_MainInstr {
            get {
                return ResourceManager.GetString("DIA009_MainInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        internal static string DIA009_Title {
            get {
                return ResourceManager.GetString("DIA009_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafting.
        /// </summary>
        internal static string Drafting {
            get {
                return ResourceManager.GetString("Drafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send bug report..
        /// </summary>
        internal static string ErrorDialog_Command1 {
            get {
                return ResourceManager.GetString("ErrorDialog_Command1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something unexpected has happened and the command cannot complete. More information can be found below..
        /// </summary>
        internal static string ErrorDialog_MainCont {
            get {
                return ResourceManager.GetString("ErrorDialog_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has encountered an error and cannot complete..
        /// </summary>
        internal static string ErrorDialog_MainInst {
            get {
                return ResourceManager.GetString("ErrorDialog_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string ErrorDialog_Title {
            get {
                return ResourceManager.GetString("ErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User License Agreement.
        /// </summary>
        internal static string EULA_IconTip {
            get {
                return ResourceManager.GetString("EULA_IconTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULA.
        /// </summary>
        internal static string EULA_Title {
            get {
                return ResourceManager.GetString("EULA_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        internal static string FilterDotDotDot {
            get {
                return ResourceManager.GetString("FilterDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components using:.
        /// </summary>
        internal static string FPC_ComponentsUsing {
            get {
                return ResourceManager.GetString("FPC_ComponentsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default to None.
        /// </summary>
        internal static string FPC_Default2NoneSolidMenuitem {
            get {
                return ResourceManager.GetString("FPC_Default2NoneSolidMenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The items you selected had no fill patterns that could be worked on. All the patterns will be shown for editing..
        /// </summary>
        internal static string FPC_DIA001_NoPattern {
            get {
                return ResourceManager.GetString("FPC_DIA001_NoPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set background pattern of filled region type {0} to pattern {1}..
        /// </summary>
        internal static string FPC_DIA004_MainCont {
            get {
                return ResourceManager.GetString("FPC_DIA004_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pattern is not a drafting pattern. The filled region type will remain unchanged and the fill pattern {0} will not be removed..
        /// </summary>
        internal static string FPC_DIA004_MainInst {
            get {
                return ResourceManager.GetString("FPC_DIA004_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families using:.
        /// </summary>
        internal static string FPC_FamiliesUsing {
            get {
                return ResourceManager.GetString("FPC_FamiliesUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleans redundant fill patterns from a project file..
        /// </summary>
        internal static string FPC_IconTip {
            get {
                return ResourceManager.GetString("FPC_IconTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Angle:.
        /// </summary>
        internal static string FPC_LineAngle {
            get {
                return ResourceManager.GetString("FPC_LineAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Spacing 1:.
        /// </summary>
        internal static string FPC_LineSpacing1 {
            get {
                return ResourceManager.GetString("FPC_LineSpacing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Spacing 2:.
        /// </summary>
        internal static string FPC_LineSpacing2 {
            get {
                return ResourceManager.GetString("FPC_LineSpacing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern &quot;{0}&quot; is already being convert to &quot;{1}&quot;. Skipping it..
        /// </summary>
        internal static string FPC_LOAD_RSLT_AlreadyConv {
            get {
                return ResourceManager.GetString("FPC_LOAD_RSLT_AlreadyConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set pattern &quot;{0}&quot; to be changed to &quot;{1}&quot;..
        /// </summary>
        internal static string FPC_LOAD_RSLT_Change {
            get {
                return ResourceManager.GetString("FPC_LOAD_RSLT_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set pattern &quot;{0}&quot; to be changed to &quot;{1}&quot; and then delete the pattern..
        /// </summary>
        internal static string FPC_LOAD_RSLT_ChangeAndDel {
            get {
                return ResourceManager.GetString("FPC_LOAD_RSLT_ChangeAndDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find pattern &quot;{0}&quot;. Skipping it..
        /// </summary>
        internal static string FPC_LOAD_RSLT_NoPatt {
            get {
                return ResourceManager.GetString("FPC_LOAD_RSLT_NoPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find pattern &quot;{0}&quot; to convert to. Skipping it..
        /// </summary>
        internal static string FPC_LOAD_RSLT_NoPatt2Conv {
            get {
                return ResourceManager.GetString("FPC_LOAD_RSLT_NoPatt2Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template had {0} style items. {1} of them were successfully applied..
        /// </summary>
        internal static string FPC_LOAD_RSLT_Summary {
            get {
                return ResourceManager.GetString("FPC_LOAD_RSLT_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template results.
        /// </summary>
        internal static string FPC_LOAD_RSLTWIN_Title {
            get {
                return ResourceManager.GetString("FPC_LOAD_RSLTWIN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials using:.
        /// </summary>
        internal static string FPC_MaterialsUsing {
            get {
                return ResourceManager.GetString("FPC_MaterialsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string FPC_None {
            get {
                return ResourceManager.GetString("FPC_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Type:.
        /// </summary>
        internal static string FPC_PatternType {
            get {
                return ResourceManager.GetString("FPC_PatternType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned family : .
        /// </summary>
        internal static string FPC_Progress {
            get {
                return ResourceManager.GetString("FPC_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Types using:.
        /// </summary>
        internal static string FPC_RegionsUsing {
            get {
                return ResourceManager.GetString("FPC_RegionsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed family {0} : {1}..
        /// </summary>
        internal static string FPC_RSLT_ChangedFamily {
            get {
                return ResourceManager.GetString("FPC_RSLT_ChangedFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted &quot;Course Scale Fill Pattern&quot; on {0} to {1} pattern..
        /// </summary>
        internal static string FPC_RSLT_ConvCourseFP {
            get {
                return ResourceManager.GetString("FPC_RSLT_ConvCourseFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted cut background pattern on material {0} to {1} pattern..
        /// </summary>
        internal static string FPC_RSLT_ConvCutBgPatt {
            get {
                return ResourceManager.GetString("FPC_RSLT_ConvCutBgPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted cut foreground pattern on material {0} to {1} pattern..
        /// </summary>
        internal static string FPC_RSLT_ConvCutFgPatt {
            get {
                return ResourceManager.GetString("FPC_RSLT_ConvCutFgPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted surface background pattern on material {0} to {1} pattern..
        /// </summary>
        internal static string FPC_RSLT_ConvSurfBgPatt {
            get {
                return ResourceManager.GetString("FPC_RSLT_ConvSurfBgPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted surface foreground pattern on material {0} to {1} pattern..
        /// </summary>
        internal static string FPC_RSLT_ConvSurfFgPatt {
            get {
                return ResourceManager.GetString("FPC_RSLT_ConvSurfFgPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set pattern on filled region type {0} to {1}..
        /// </summary>
        internal static string FPC_RSLT_FillReg_Conv {
            get {
                return ResourceManager.GetString("FPC_RSLT_FillReg_Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set pattern on filled region type {0} to Solid..
        /// </summary>
        internal static string FPC_RSLT_FillReg_Solid {
            get {
                return ResourceManager.GetString("FPC_RSLT_FillReg_Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set background pattern on filled region type {0} to {1}..
        /// </summary>
        internal static string FPC_RSLT_FillRegBg_Conv {
            get {
                return ResourceManager.GetString("FPC_RSLT_FillRegBg_Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed background pattern on filled region type {0}..
        /// </summary>
        internal static string FPC_RSLT_FillRegBg_Rem {
            get {
                return ResourceManager.GetString("FPC_RSLT_FillRegBg_Rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set foreground pattern on filled region type {0} to {1}..
        /// </summary>
        internal static string FPC_RSLT_FillRegFg_Conv {
            get {
                return ResourceManager.GetString("FPC_RSLT_FillRegFg_Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed foreground pattern on filled region type {0}..
        /// </summary>
        internal static string FPC_RSLT_FillRegFg_Rem {
            get {
                return ResourceManager.GetString("FPC_RSLT_FillRegFg_Rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set background of filled region type {0} to pattern {1}. This pattern is not a drafting pattern..
        /// </summary>
        internal static string FPC_RSLT_FrtcFailed {
            get {
                return ResourceManager.GetString("FPC_RSLT_FrtcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set pattern on filled region type {0} to Solid..
        /// </summary>
        internal static string FPC_RSLT_RegPattSolid {
            get {
                return ResourceManager.GetString("FPC_RSLT_RegPattSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed &quot;Course Scale Fill Pattern&quot; on {0}..
        /// </summary>
        internal static string FPC_RSLT_RemCourseFP {
            get {
                return ResourceManager.GetString("FPC_RSLT_RemCourseFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed cut background pattern on material {0}..
        /// </summary>
        internal static string FPC_RSLT_RemCutBgPatt {
            get {
                return ResourceManager.GetString("FPC_RSLT_RemCutBgPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed cut foreground pattern on material {0}..
        /// </summary>
        internal static string FPC_RSLT_RemCutFgPatt {
            get {
                return ResourceManager.GetString("FPC_RSLT_RemCutFgPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed surface background pattern on material {0}..
        /// </summary>
        internal static string FPC_RSLT_RemSurfBgPatt {
            get {
                return ResourceManager.GetString("FPC_RSLT_RemSurfBgPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed surface foreground pattern on material {0}..
        /// </summary>
        internal static string FPC_RSLT_RemSurfFgPatt {
            get {
                return ResourceManager.GetString("FPC_RSLT_RemSurfFgPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set pattern on filled region type {0} to {1}..
        /// </summary>
        internal static string FPC_RSLT_SetPatt {
            get {
                return ResourceManager.GetString("FPC_RSLT_SetPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a style to convert existing assets to..
        /// </summary>
        internal static string FPC_StyleCombobox {
            get {
                return ResourceManager.GetString("FPC_StyleCombobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Type:.
        /// </summary>
        internal static string FPC_TargetType {
            get {
                return ResourceManager.GetString("FPC_TargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Pattern Cleaner.
        /// </summary>
        internal static string FPC_Title_MainWindow {
            get {
                return ResourceManager.GetString("FPC_Title_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Pattern
        ///Cleaner.
        /// </summary>
        internal static string FPC_Title_Ribbon {
            get {
                return ResourceManager.GetString("FPC_Title_Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert family.
        /// </summary>
        internal static string FPC_TRANS_ConvertFamily {
            get {
                return ResourceManager.GetString("FPC_TRANS_ConvertFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default to Delete Regions.
        /// </summary>
        internal static string FRTC_Default2DeleteMenuitem {
            get {
                return ResourceManager.GetString("FRTC_Default2DeleteMenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} region(s)..
        /// </summary>
        internal static string FRTC_DeletedXRegions {
            get {
                return ResourceManager.GetString("FRTC_DeletedXRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Regions.
        /// </summary>
        internal static string FRTC_DeleteRegion {
            get {
                return ResourceManager.GetString("FRTC_DeleteRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no fill region type to convert another fill region type to and Revit project files must have at least one fill region type at all times..
        /// </summary>
        internal static string FRTC_DIA001_MainCont {
            get {
                return ResourceManager.GetString("FRTC_DIA001_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is only one fill region type in this project file..
        /// </summary>
        internal static string FRTC_DIA001_MainInst {
            get {
                return ResourceManager.GetString("FRTC_DIA001_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filled region type &quot;{0}&quot; will not be deleted..
        /// </summary>
        internal static string FRTC_DIA002_MainCont {
            get {
                return ResourceManager.GetString("FRTC_DIA002_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing all filled region types from a Revit project is not allowed..
        /// </summary>
        internal static string FRTC_DIA002_MainInst {
            get {
                return ResourceManager.GetString("FRTC_DIA002_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected element was not a region..
        /// </summary>
        internal static string FRTC_DIA003_Txt {
            get {
                return ResourceManager.GetString("FRTC_DIA003_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The items you selected were not filled regions. All the styles will be shown for editing..
        /// </summary>
        internal static string FRTC_DIA004_MainInst {
            get {
                return ResourceManager.GetString("FRTC_DIA004_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No regions found.
        /// </summary>
        internal static string FRTC_DIA004_Title {
            get {
                return ResourceManager.GetString("FRTC_DIA004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleans redundant fill region types from a project file..
        /// </summary>
        internal static string FRTC_IconTip {
            get {
                return ResourceManager.GetString("FRTC_IconTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; is already being converted to &quot;{1}&quot;. Skipping it..
        /// </summary>
        internal static string FRTC_LOAD_RSLT_AlreadyConv {
            get {
                return ResourceManager.GetString("FRTC_LOAD_RSLT_AlreadyConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set type &quot;{0}&quot; to be changed to &quot;{1}&quot;..
        /// </summary>
        internal static string FRTC_LOAD_RSLT_Change {
            get {
                return ResourceManager.GetString("FRTC_LOAD_RSLT_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set type &quot;{0}&quot; to be changed to &quot;{1}&quot; and then delete the type..
        /// </summary>
        internal static string FRTC_LOAD_RSLT_ChangeAndDel {
            get {
                return ResourceManager.GetString("FRTC_LOAD_RSLT_ChangeAndDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find type &quot;{0}&quot;. Skipping it..
        /// </summary>
        internal static string FRTC_LOAD_RSLT_NoType {
            get {
                return ResourceManager.GetString("FRTC_LOAD_RSLT_NoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find type &quot;{0}&quot; to convert to. Skipping it..
        /// </summary>
        internal static string FRTC_LOAD_RSLT_NoType2Conv {
            get {
                return ResourceManager.GetString("FRTC_LOAD_RSLT_NoType2Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string FRTC_NoFPName {
            get {
                return ResourceManager.GetString("FRTC_NoFPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted {0} filled regions to &quot;{1}&quot;.
        /// </summary>
        internal static string FRTC_RSLT_ConvertedRegionTypes {
            get {
                return ResourceManager.GetString("FRTC_RSLT_ConvertedRegionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} filled region types.
        /// </summary>
        internal static string FRTC_RSLT_DeletedRegionTypes {
            get {
                return ResourceManager.GetString("FRTC_RSLT_DeletedRegionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select style to convert to or &apos;Delete Regions&apos; to remove regions from project.
        /// </summary>
        internal static string FRTC_StyleCombobox {
            get {
                return ResourceManager.GetString("FRTC_StyleCombobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string FRTC_Tab_Bg {
            get {
                return ResourceManager.GetString("FRTC_Tab_Bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fore.
        /// </summary>
        internal static string FRTC_Tab_Fg {
            get {
                return ResourceManager.GetString("FRTC_Tab_Fg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Region Type Cleaner.
        /// </summary>
        internal static string FRTC_Title_MainWindow {
            get {
                return ResourceManager.GetString("FRTC_Title_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Region
        ///Type Cleaner.
        /// </summary>
        internal static string FRTC_Title_Ribbon {
            get {
                return ResourceManager.GetString("FRTC_Title_Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help for using the Project Sweeper tools..
        /// </summary>
        internal static string HELP_IconTip {
            get {
                return ResourceManager.GetString("HELP_IconTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectSweeper.chm.
        /// </summary>
        internal static string HelpFile {
            get {
                return ResourceManager.GetString("HelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I am connected to the internet. Let me submit a bug report..
        /// </summary>
        internal static string LIC_DIA001_Command1 {
            get {
                return ResourceManager.GetString("LIC_DIA001_Command1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I am NOT connected to the internet. Let me connect and try again later..
        /// </summary>
        internal static string LIC_DIA001_Command2 {
            get {
                return ResourceManager.GetString("LIC_DIA001_Command2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license server could not be reached at this time. Are you connected to the internet?.
        /// </summary>
        internal static string LIC_DIA001_MainCont {
            get {
                return ResourceManager.GetString("LIC_DIA001_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve a license from the server..
        /// </summary>
        internal static string LIC_DIA001_MainInst {
            get {
                return ResourceManager.GetString("LIC_DIA001_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing error.
        /// </summary>
        internal static string LIC_DIA001_TItle {
            get {
                return ResourceManager.GetString("LIC_DIA001_TItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your IT department to ask for access..
        /// </summary>
        internal static string LIC_DIA002_MainCont {
            get {
                return ResourceManager.GetString("LIC_DIA002_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to use this app..
        /// </summary>
        internal static string LIC_DIA002_MainInst {
            get {
                return ResourceManager.GetString("LIC_DIA002_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        internal static string LIC_DIA002_Title {
            get {
                return ResourceManager.GetString("LIC_DIA002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application must check if you are authorized to use it. Login to Autodesk 360 using the same account you used to purchase this app. An internet connection is required..
        /// </summary>
        internal static string LIC_DIA003_MainCont {
            get {
                return ResourceManager.GetString("LIC_DIA003_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to Autodesk 360 first..
        /// </summary>
        internal static string LIC_DIA003_MainInst {
            get {
                return ResourceManager.GetString("LIC_DIA003_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LIC_DIA003_Title {
            get {
                return ResourceManager.GetString("LIC_DIA003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you login into Autodesk 360 with the same account you used to buy this app. If the app was purchased under a company account, contact your IT department to allow you access..
        /// </summary>
        internal static string LIC_DIA004_MainCont {
            get {
                return ResourceManager.GetString("LIC_DIA004_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of purchased licenses has already been used up. More licenses will need to be purchased before Project Sweeper can be installed on more computers..
        /// </summary>
        internal static string LIC_MSG_MaxLic {
            get {
                return ResourceManager.GetString("LIC_MSG_MaxLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license server could not be contacted..
        /// </summary>
        internal static string LIC_MSG_NoSrvr {
            get {
                return ResourceManager.GetString("LIC_MSG_NoSrvr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No license found..
        /// </summary>
        internal static string LIC_MSG_NotFound {
            get {
                return ResourceManager.GetString("LIC_MSG_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find user.dat file..
        /// </summary>
        internal static string LIC_MSG_NoUserDat {
            get {
                return ResourceManager.GetString("LIC_MSG_NoUserDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This license has been revoked..
        /// </summary>
        internal static string LIC_MSG_Revoked {
            get {
                return ResourceManager.GetString("LIC_MSG_Revoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules\Templates using {0}.
        /// </summary>
        internal static string ListUsers_Title1 {
            get {
                return ResourceManager.GetString("ListUsers_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets using {0}.
        /// </summary>
        internal static string ListUsers_Title2 {
            get {
                return ResourceManager.GetString("ListUsers_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Users.
        /// </summary>
        internal static string ListUsersButton {
            get {
                return ResourceManager.GetString("ListUsersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View names starting with &apos;&gt;&apos; are schedules or view templates and cannot be viewed in the preview window..
        /// </summary>
        internal static string ListViews_DIA001_MainInst {
            get {
                return ResourceManager.GetString("ListViews_DIA001_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule view.
        /// </summary>
        internal static string ListViews_DIA001_Title {
            get {
                return ResourceManager.GetString("ListViews_DIA001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click a view on the list to display it here..
        /// </summary>
        internal static string ListViews_PromptText {
            get {
                return ResourceManager.GetString("ListViews_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views using {0}.
        /// </summary>
        internal static string ListViews_Title {
            get {
                return ResourceManager.GetString("ListViews_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Views.
        /// </summary>
        internal static string ListViewsButton {
            get {
                return ResourceManager.GetString("ListViewsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string LoadButton {
            get {
                return ResourceManager.GetString("LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} line pattern(s)..
        /// </summary>
        internal static string LPC_2016Removed {
            get {
                return ResourceManager.GetString("LPC_2016Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to limitations in Revit, this app cannot determine which line styles are using which line patterns. Deleting a line pattern that is currently being used by a line style will result in that line style switching to the Solid line pattern..
        /// </summary>
        internal static string LPC_2016Warning {
            get {
                return ResourceManager.GetString("LPC_2016Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default to Solid.
        /// </summary>
        internal static string LPC_Default2SolidMenuitem {
            get {
                return ResourceManager.GetString("LPC_Default2SolidMenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line pattern of the selected element was &quot;Solid&quot; and cannot be changed or the selected element was not a detail or model line. Starting in multi-mode..
        /// </summary>
        internal static string LPC_DIA001_MainInst {
            get {
                return ResourceManager.GetString("LPC_DIA001_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patterns found.
        /// </summary>
        internal static string LPC_DIA001_TItle {
            get {
                return ResourceManager.GetString("LPC_DIA001_TItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleans redundant line patterns from a project file..
        /// </summary>
        internal static string LPC_IconTip {
            get {
                return ResourceManager.GetString("LPC_IconTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line styles using:.
        /// </summary>
        internal static string LPC_LineStylesUsing {
            get {
                return ResourceManager.GetString("LPC_LineStylesUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern:.
        /// </summary>
        internal static string LPC_Pattern {
            get {
                return ResourceManager.GetString("LPC_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted the following style(s) to pattern : {0}.
        /// </summary>
        internal static string LPC_RSLT_ConvertedStyle {
            get {
                return ResourceManager.GetString("LPC_RSLT_ConvertedStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        internal static string LPC_Solid {
            get {
                return ResourceManager.GetString("LPC_Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a style to convert existing assets to..
        /// </summary>
        internal static string LPC_StyleCombobox {
            get {
                return ResourceManager.GetString("LPC_StyleCombobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Pattern Cleaner.
        /// </summary>
        internal static string LPC_Title_MainWindow {
            get {
                return ResourceManager.GetString("LPC_Title_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Pattern
        ///Cleaner.
        /// </summary>
        internal static string LPC_Title_Ribbon {
            get {
                return ResourceManager.GetString("LPC_Title_Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default to Delete Lines.
        /// </summary>
        internal static string LSC_Default2DeleteMenuitem {
            get {
                return ResourceManager.GetString("LSC_Default2DeleteMenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Lines.
        /// </summary>
        internal static string LSC_DeleteLines {
            get {
                return ResourceManager.GetString("LSC_DeleteLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Lines.
        /// </summary>
        internal static string LSC_DetailLines {
            get {
                return ResourceManager.GetString("LSC_DetailLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected element was not a line..
        /// </summary>
        internal static string LSC_DIA005_Txt {
            get {
                return ResourceManager.GetString("LSC_DIA005_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert line to Thin Line style so style {0} can be removed..
        /// </summary>
        internal static string LSC_DIA007_Command1 {
            get {
                return ResourceManager.GetString("LSC_DIA007_Command1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not remove style {0} and keep line as is..
        /// </summary>
        internal static string LSC_DIA007_Command2 {
            get {
                return ResourceManager.GetString("LSC_DIA007_Command2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this line will leave the filled\masking region open and therefore invalid. What would you like to do?.
        /// </summary>
        internal static string LSC_DIA007_MainCont {
            get {
                return ResourceManager.GetString("LSC_DIA007_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A line using the {0} style was found in a filled\masking region..
        /// </summary>
        internal static string LSC_DIA007_MainInst {
            get {
                return ResourceManager.GetString("LSC_DIA007_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region found.
        /// </summary>
        internal static string LSC_DIA007_Title {
            get {
                return ResourceManager.GetString("LSC_DIA007_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify detail group &quot;{0}&quot; because it is attached to a model group. Line style &quot;{1}&quot; will not be deleted..
        /// </summary>
        internal static string LSC_DIA008_MainInst {
            get {
                return ResourceManager.GetString("LSC_DIA008_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported detail group.
        /// </summary>
        internal static string LSC_DIA008_Title {
            get {
                return ResourceManager.GetString("LSC_DIA008_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected element was not a detail or model line. Starting in multi-mode..
        /// </summary>
        internal static string LSC_DIA009_MainInstr {
            get {
                return ResourceManager.GetString("LSC_DIA009_MainInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No styles found.
        /// </summary>
        internal static string LSC_DIA009_Title {
            get {
                return ResourceManager.GetString("LSC_DIA009_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleans redundant line styles from a project file..
        /// </summary>
        internal static string LSC_IconTip {
            get {
                return ResourceManager.GetString("LSC_IconTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Lines.
        /// </summary>
        internal static string LSC_ModelLines {
            get {
                return ResourceManager.GetString("LSC_ModelLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        internal static string LSC_Pattern {
            get {
                return ResourceManager.GetString("LSC_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted {0} lines to Thin Lines to maintain filled\masking regions.
        /// </summary>
        internal static string LSC_RSLT_Convert2Thin {
            get {
                return ResourceManager.GetString("LSC_RSLT_Convert2Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted {0} lines to &quot;{1}&quot;.
        /// </summary>
        internal static string LSC_RSLT_ConvertedLines {
            get {
                return ResourceManager.GetString("LSC_RSLT_ConvertedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} lines.
        /// </summary>
        internal static string LSC_RSLT_DeletedLines {
            get {
                return ResourceManager.GetString("LSC_RSLT_DeletedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} lines using the {1} style..
        /// </summary>
        internal static string LSC_RSLT_FoundLines {
            get {
                return ResourceManager.GetString("LSC_RSLT_FoundLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will not be deleted to maintain filled\masking regions..
        /// </summary>
        internal static string LSC_RSLT_NoDelete {
            get {
                return ResourceManager.GetString("LSC_RSLT_NoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select line style to convert lines to or &apos;Delete Lines&apos; to remove lines from project.
        /// </summary>
        internal static string LSC_StyleCombobox {
            get {
                return ResourceManager.GetString("LSC_StyleCombobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Style Cleaner.
        /// </summary>
        internal static string LSC_Title_MainWindow {
            get {
                return ResourceManager.GetString("LSC_Title_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Style
        ///Cleaner.
        /// </summary>
        internal static string LSC_Title_Ribbon {
            get {
                return ResourceManager.GetString("LSC_Title_Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule\Template.
        /// </summary>
        internal static string LUW_Asset {
            get {
                return ResourceManager.GetString("LUW_Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets using {0}.
        /// </summary>
        internal static string LUW_Title_Txt {
            get {
                return ResourceManager.GetString("LUW_Title_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string PROG_Cancelled {
            get {
                return ResourceManager.GetString("PROG_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection.
        /// </summary>
        internal static string Projection {
            get {
                return ResourceManager.GetString("Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge Unused.
        /// </summary>
        internal static string PurgeUnusedButton {
            get {
                return ResourceManager.GetString("PurgeUnusedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string ResetAllButton {
            get {
                return ResourceManager.GetString("ResetAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset pattern.
        /// </summary>
        internal static string ResetPatternMenuitem {
            get {
                return ResourceManager.GetString("ResetPatternMenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset style.
        /// </summary>
        internal static string ResetStyleMenuitem {
            get {
                return ResourceManager.GetString("ResetStyleMenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted {0} style(s)..
        /// </summary>
        internal static string RSLT_Converted {
            get {
                return ResourceManager.GetString("RSLT_Converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} style(s)..
        /// </summary>
        internal static string RSLT_Deleted {
            get {
                return ResourceManager.GetString("RSLT_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} style(s)..
        /// </summary>
        internal static string RSLT_Found {
            get {
                return ResourceManager.GetString("RSLT_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} was not ungrouped. {1} will not be removed..
        /// </summary>
        internal static string RSLT_NotUngrouped {
            get {
                return ResourceManager.GetString("RSLT_NotUngrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style queued to be removed..
        /// </summary>
        internal static string RSLT_Queue {
            get {
                return ResourceManager.GetString("RSLT_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern queued to be removed..
        /// </summary>
        internal static string RSLT_Queue_Pattern {
            get {
                return ResourceManager.GetString("RSLT_Queue_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} style(s)..
        /// </summary>
        internal static string RSLT_Removed {
            get {
                return ResourceManager.GetString("RSLT_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style {0} removed from queue.
        /// </summary>
        internal static string RSLT_RemoveQueue {
            get {
                return ResourceManager.GetString("RSLT_RemoveQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style {0} was removed from the project..
        /// </summary>
        internal static string RSLT_SingleMode {
            get {
                return ResourceManager.GetString("RSLT_SingleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Report.
        /// </summary>
        internal static string RSLT_Summary {
            get {
                return ResourceManager.GetString("RSLT_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungrouping {0} group.
        /// </summary>
        internal static string RSLT_Ungrouped {
            get {
                return ResourceManager.GetString("RSLT_Ungrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string RSLTWIN_Save {
            get {
                return ResourceManager.GetString("RSLTWIN_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for .
        /// </summary>
        internal static string RSLTWIN_Title {
            get {
                return ResourceManager.GetString("RSLTWIN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default pattern.
        /// </summary>
        internal static string SetDefaultPatternMenuitem {
            get {
                return ResourceManager.GetString("SetDefaultPatternMenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default style.
        /// </summary>
        internal static string SetDefaultStyleMenuitem {
            get {
                return ResourceManager.GetString("SetDefaultStyleMenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Crosshatch.
        /// </summary>
        internal static string Simple_Crosshatch {
            get {
                return ResourceManager.GetString("Simple_Crosshatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Parallel Lines.
        /// </summary>
        internal static string Simple_Parallel_Lines {
            get {
                return ResourceManager.GetString("Simple_Parallel_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore case.
        /// </summary>
        internal static string TEMPLATEWIN_IgnoreCase {
            get {
                return ResourceManager.GetString("TEMPLATEWIN_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this template to create a new saved template. You will be prompted to name it. Or select an existing template to overwrite it. Replace this comment with something meaningful to you..
        /// </summary>
        internal static string TEMPLATEWIN_NewTemplateComment {
            get {
                return ResourceManager.GetString("TEMPLATEWIN_NewTemplateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Create New Template&gt;.
        /// </summary>
        internal static string TEMPLATEWIN_NewTemplatename {
            get {
                return ResourceManager.GetString("TEMPLATEWIN_NewTemplatename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Templates.
        /// </summary>
        internal static string TEMPLATEWIN_SaveTemplates {
            get {
                return ResourceManager.GetString("TEMPLATEWIN_SaveTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Items:.
        /// </summary>
        internal static string TEMPLATEWIN_StyleItems {
            get {
                return ResourceManager.GetString("TEMPLATEWIN_StyleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Comment.
        /// </summary>
        internal static string TEMPLATEWIN_TemplatesComment {
            get {
                return ResourceManager.GetString("TEMPLATEWIN_TemplatesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string TEMPLATEWIN_Title_Templates {
            get {
                return ResourceManager.GetString("TEMPLATEWIN_Title_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new style for.
        /// </summary>
        internal static string Title_SingleWindow {
            get {
                return ResourceManager.GetString("Title_SingleWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new pattern for.
        /// </summary>
        internal static string Title_SingleWindow_Pattern {
            get {
                return ResourceManager.GetString("Title_SingleWindow_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bg.
        /// </summary>
        internal static string TSC_Bg {
            get {
                return ResourceManager.GetString("TSC_Bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string TSC_Box {
            get {
                return ResourceManager.GetString("TSC_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Styles.
        /// </summary>
        internal static string TSC_CompareButton {
            get {
                return ResourceManager.GetString("TSC_CompareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default to Delete Notes.
        /// </summary>
        internal static string TSC_Default2DeleteMenuitem {
            get {
                return ResourceManager.GetString("TSC_Default2DeleteMenuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Notes.
        /// </summary>
        internal static string TSC_DeleteNotes {
            get {
                return ResourceManager.GetString("TSC_DeleteNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no text style to convert another text style to and Revit project files must have at least one text style at all times..
        /// </summary>
        internal static string TSC_DIA001_MainCont {
            get {
                return ResourceManager.GetString("TSC_DIA001_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is only one text style in this project file..
        /// </summary>
        internal static string TSC_DIA001_MainInst {
            get {
                return ResourceManager.GetString("TSC_DIA001_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text style &quot;{0}&quot; will not be deleted..
        /// </summary>
        internal static string TSC_DIA002_MainCont {
            get {
                return ResourceManager.GetString("TSC_DIA002_MainCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing all text styles from a Revit project is not allowed..
        /// </summary>
        internal static string TSC_DIA002_MainInst {
            get {
                return ResourceManager.GetString("TSC_DIA002_MainInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected element was not a note..
        /// </summary>
        internal static string TSC_DIA003_Txt {
            get {
                return ResourceManager.GetString("TSC_DIA003_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string TSC_Font {
            get {
                return ResourceManager.GetString("TSC_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        internal static string TSC_GraphicsTxt {
            get {
                return ResourceManager.GetString("TSC_GraphicsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleans redundant text styles from a project file..
        /// </summary>
        internal static string TSC_IconTip {
            get {
                return ResourceManager.GetString("TSC_IconTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted {0} notes to &quot;{1}&quot;.
        /// </summary>
        internal static string TSC_RSLT_ConvertedNotes {
            get {
                return ResourceManager.GetString("TSC_RSLT_ConvertedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style on schedule {0} willl be set to system default.
        /// </summary>
        internal static string TSC_RSLT_ConvSched2Default {
            get {
                return ResourceManager.GetString("TSC_RSLT_ConvSched2Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted style on schedule: {0}.
        /// </summary>
        internal static string TSC_RSLT_ConvSchedule {
            get {
                return ResourceManager.GetString("TSC_RSLT_ConvSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} note(s).
        /// </summary>
        internal static string TSC_RSLT_DeletedNotes {
            get {
                return ResourceManager.GetString("TSC_RSLT_DeletedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string TSC_Size {
            get {
                return ResourceManager.GetString("TSC_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select style to convert to or &apos;Delete Notes&apos; to remove notes from project.
        /// </summary>
        internal static string TSC_StyleCombobox {
            get {
                return ResourceManager.GetString("TSC_StyleCombobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TSC_TextTxt {
            get {
                return ResourceManager.GetString("TSC_TextTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Style Cleaner.
        /// </summary>
        internal static string TSC_Title_MainWindow {
            get {
                return ResourceManager.GetString("TSC_Title_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Style
        ///Cleaner.
        /// </summary>
        internal static string TSC_Title_Ribbon {
            get {
                return ResourceManager.GetString("TSC_Title_Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string TSC_Used {
            get {
                return ResourceManager.GetString("TSC_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Style Comparer.
        /// </summary>
        internal static string TSCC_Title_Window {
            get {
                return ResourceManager.GetString("TSCC_Title_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection.
        /// </summary>
        internal static string TXT_BadSelection {
            get {
                return ResourceManager.GetString("TXT_BadSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        internal static string TXT_Colour {
            get {
                return ResourceManager.GetString("TXT_Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click a view on the list to display it here..
        /// </summary>
        internal static string TXT_DblClickView {
            get {
                return ResourceManager.GetString("TXT_DblClickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Style.
        /// </summary>
        internal static string TXT_NewStyle {
            get {
                return ResourceManager.GetString("TXT_NewStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP.
        /// </summary>
        internal static string TXT_Pattern {
            get {
                return ResourceManager.GetString("TXT_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Style.
        /// </summary>
        internal static string TXT_SelectedStyle {
            get {
                return ResourceManager.GetString("TXT_SelectedStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string TXT_Success {
            get {
                return ResourceManager.GetString("TXT_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Used.
        /// </summary>
        internal static string TXT_TimesUsed {
            get {
                return ResourceManager.GetString("TXT_TimesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string TXT_Warning {
            get {
                return ResourceManager.GetString("TXT_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string TXT_Weight {
            get {
                return ResourceManager.GetString("TXT_Weight", resourceCulture);
            }
        }
    }
}
